Making pip compliant
Currently installation fail due to `PEP-0639`:

Example:
```
SIFTS git:(development) pip install .
Processing /Users/ahsan/SIFTS
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)  # type: ignore[return-value]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 160, in setup
          dist.parse_config_files()
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 762, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 73, in apply_configuration
          return _apply(dist, config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 61, in apply
          dist._finalize_license_expression()
        File "/private/var/folders/wl/qfv_bg4j0pv3_8bfwvbq7v9h0000gp/T/pip-build-env-_jgvjed_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 430, in _finalize_license_expression
          raise InvalidConfigError(
      setuptools.errors.InvalidConfigError: License classifiers have been superseded by license expressions (see https://peps.python.org/pep-0639/). Please remove:

      License :: OSI Approved :: Apache Software License
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

I am removing license info from classifier to fix this issue.